### ISSUE TITLE
Error limit exceeded

### ISSUE THREAD

**Issue by zhihaojin** [pjaselin/Cubist#145] opened 2024-05-07 23:59 UTC
I've encountered a problem while using the fitted Cubist model for predictions. It seems that the issue arises when some variables in the prediction dataset fall outside the range of the training dataset. I tried to adjust the extrapolation percent but it did not help. Could you please provide guidance or a potential solution for handling this?

Thank you for your assistance!

Here is the error message:

  File "/panfs/Model_Prediction/1_predict_base.py", line 111, in <mod                                ule>
    predictions = loaded_model.predict(prediction_data_spe[columns_to_model_f])
  File "/home/miniconda3/lib/python3.9/site-packages/cubist/cubist.py", line 446, in pre                                dict
    raise CubistError(output)
cubist.exceptions.CubistError:
*** line 1154801 of `undefined.cases':
    unexpected eof while reading attribute `precipitation'

**Comment by pjaselin** [comment] 2024-05-15 23:44
Hi @zhihaojin, thanks for raising this! I was trying to figure out what would trigger this code in the predict method for a unit test anyways. Would you be able to provide a minimum reproducible example for this?

**Comment by pjaselin** [comment] 2024-05-18 17:27
I just started looking into this and I'm not sure if I can reproduce it. I tried but using a constant multiplier to change the input dataset and using two random datasets and neither worked so an example would help.

**Comment by pjaselin** [comment] 2024-05-19 18:12
Any idea at what number of rows it breaks (assuming you mean rows and not columns)? It would be good to verify and handle that in the code (like run prediction in chunks and return the complete result).

**Comment by pjaselin** [comment] 2024-06-19 13:53
Closing since this appears safe predicting under 10M rows and I can't go to a higher order of magnitude without running out of memory on my laptop in allocating the prediction data frame or the process getting killed (assuming OOM as well). I'd investigate further if more people have issues though.

**Closed by pjaselin** 2024-06-19 13:53 UTC
