### ISSUE TITLE
Installation error on Windows 10

### ISSUE THREAD

**Issue by eggy00** [pjaselin/Cubist#71] opened 2021-10-10 20:43 UTC
pip install on Windows 10 gives : ERROR: Could not build wheels for cubist which use PEP 517 and cannot be installed directly.
(Looking at error log, the problem might be due to differences in MSVC on Windows (vs eg UNIX) which doesnt have sys/time.h:-

utility.c
  cubist/src\utility.c(42): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory

eg here: https://www.codefull.net/2015/12/systime-h-replacement-for-windows/
)

**Comment by pjaselin** [comment] 2021-11-02 04:24
duplicate of #70

**Closed by pjaselin** 2021-11-02 04:24 UTC
